apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
spec:
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      nodeSelector:
        role: main
      containers:
        - name: store-service
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/store-service:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "300m"
              memory: "600Mi"
          ports:
            - containerPort: 9007
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://$MYSQL_IP:3306/store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
            - name: SPRING_RABBITMQ_HOST
              value: $RABBITMQ_IP
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SQS_URL_STORE_ADD
              value: https://sqs.$AWS_REGION.amazonaws.com/$AWS_ACCOUNT_ID/store-add-queue
            - name: SQS_URL_STORE_UPDATE
              value: https://sqs.$AWS_REGION.amazonaws.com/$AWS_ACCOUNT_ID/store-update-queue
            - name: SQS_URL_STORE_DELETE
              value: https://sqs.$AWS_REGION.amazonaws.com/$AWS_ACCOUNT_ID/store-delete-queue
            - name: SPRING_PROFILES_ACTIVE
              value: deploy
            - name: SPRING_RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: store-service-secrets
                  key: SPRING_RABBITMQ_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-service-secrets
                  key: SPRING_RABBITMQ_PASSWORD
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: store-service-secrets
                  key: SPRING_DATASOURCE_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-service-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: STORE_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: store-service-secrets
                  key: STORE_AWS_ACCESS_KEY_ID
            - name: STORE_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: store-service-secrets
                  key: STORE_AWS_SECRET_ACCESS_KEY
