name: Build and Push Docker to AWS ECR

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'   # 원하는 버전 지정 가능 (예: 'v1.27.3')

      - name: Configure kubeconfig for EKS cluster
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name sandit-cluster

        # EKS 클러스터 접근을 위한 인증 토큰 생성 (15분짜리 임시 토큰)
        # GitHub Actions 환경에서는 자동으로 토큰 갱신이 안 되기 때문에,
        # kubectl apply 전에 수동으로 한 번 토큰 생성해서 인증 상태 확인해 줌
        # 이걸 안 넣으면 "failed to download openapi" 같은 인증 에러 발생 가능성 있음

      - name: Authenticate to EKS (generate token)
        run: |
          aws eks get-token --region ${{ secrets.AWS_REGION }} --cluster-name sandit-cluster > /dev/null

      - name: Create Kubernetes Secrets from GitHub Secrets
        run: |
          kubectl create secret generic store-service-secrets \
            --from-literal=SPRING_RABBITMQ_USER=${{ secrets.SPRING_RABBITMQ_USER }} \
            --from-literal=SPRING_RABBITMQ_PASSWORD=${{ secrets.SPRING_RABBITMQ_PASSWORD }} \
            --from-literal=STORE_AWS_ACCESS_KEY_ID=${{ secrets.STORE_AWS_ACCESS_KEY_ID }} \
            --from-literal=STORE_AWS_SECRET_ACCESS_KEY=${{ secrets.STORE_AWS_SECRET_ACCESS_KEY }} \
            --from-literal=SPRING_DATASOURCE_USER=${{ secrets.SPRING_DATASOURCE_USER }} \
            --from-literal=SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply --validate=false -f -

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t store-service:latest .

      - name: Tag Docker image
        run: |
          docker tag store-service:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/store-service:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/store-service:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
